// src/config/teamSections.js

export const TEAM_SECTION_CONFIGS = {
  hackathons: {
    pageTitle: "Hackathons",
    pageSubtitle: "Record competitions, projects, results, presentations and event memories.",
    sheetName: "Hackathons",
    idField: "EVENT_ID",
    idPrefix: "EVT",
    icon: "🏆",
    imageField: "COVER_IMAGE",
    titleField: "TITLE",
    subtitleField: "PROJECT",
    badgeField: "STATUS",
    searchFields: ["TITLE", "ORGANIZER", "PROJECT", "THEME", "MEMBERS", "TECH_STACK", "STATUS", "POSITION"],
    fields: [
      { name: "TITLE", label: "Hackathon title", type: "text", required: true, placeholder: "Example: CodeFusion 2026" },
      { name: "ORGANIZER", label: "Organizer", type: "text", required: true },
      { name: "DATE", label: "Date", type: "date", required: true },
      { name: "LOCATION", label: "Location", type: "text", placeholder: "College / city / online" },
      { name: "PROJECT", label: "Project title", type: "text", required: true },
      { name: "THEME", label: "Theme or track", type: "text" },
      { name: "MEMBERS", label: "Team members", type: "textarea", placeholder: "Separate names using commas" },
      { name: "TECH_STACK", label: "Technology stack", type: "text", placeholder: "React, Firebase, IoT..." },
      {
        name: "STATUS",
        label: "Status",
        type: "select",
        required: true,
        options: ["Participated", "Shortlisted", "Finalist", "Winner", "Runner-up", "Completed"],
      },
      { name: "POSITION", label: "Position / result", type: "text", placeholder: "Example: 2nd place" },
      { name: "DESCRIPTION", label: "Description", type: "textarea", required: true },
      { name: "GITHUB", label: "GitHub URL", type: "url" },
      { name: "DEMO", label: "Live demo URL", type: "url" },
      { name: "PPT", label: "PPT / report URL", type: "url" },
      { name: "DRIVE_FOLDER", label: "Google Drive folder URL", type: "url" },
      { name: "COVER_IMAGE", label: "Cover image URL", type: "url", help: "Use a public image link." },
    ],
    detailOrder: [
      "ORGANIZER", "DATE", "LOCATION", "PROJECT", "THEME", "MEMBERS", "TECH_STACK",
      "STATUS", "POSITION", "DESCRIPTION", "GITHUB", "DEMO", "PPT", "DRIVE_FOLDER",
    ],
  },

  gallery: {
    pageTitle: "Gallery",
    pageSubtitle: "Share hackathon, workshop, presentation and team activity photos.",
    sheetName: "Gallery",
    idField: "PHOTO_ID",
    idPrefix: "IMG",
    icon: "🖼️",
    imageField: "IMAGE_URL",
    titleField: "CAPTION",
    subtitleField: "EVENT_ID",
    searchFields: ["EVENT_ID", "CAPTION", "DATE", "UPLOADED_BY"],
    fields: [
      { name: "EVENT_ID", label: "Hackathon event ID", type: "text", required: true, placeholder: "Example: EVT-..." },
      { name: "IMAGE_URL", label: "Photo URL", type: "url", required: true, help: "Use a public Google Drive or image-hosting link." },
      { name: "CAPTION", label: "Caption", type: "textarea", required: true },
      { name: "DATE", label: "Photo date", type: "date", required: true },
    ],
    detailOrder: ["EVENT_ID", "CAPTION", "DATE", "UPLOADED_BY", "IMAGE_URL"],
  },

  projects: {
    pageTitle: "Projects",
    pageSubtitle: "Showcase team projects, demos, source code and current development status.",
    sheetName: "Projects",
    idField: "PROJECT_ID",
    idPrefix: "PRJ",
    icon: "💻",
    imageField: "IMAGE",
    titleField: "TITLE",
    subtitleField: "CATEGORY",
    badgeField: "STATUS",
    searchFields: ["TITLE", "CATEGORY", "MEMBERS", "TECH_STACK", "DESCRIPTION", "STATUS"],
    fields: [
      { name: "TITLE", label: "Project title", type: "text", required: true },
      {
        name: "CATEGORY",
        label: "Category",
        type: "select",
        required: true,
        options: ["Web Development", "Mobile Application", "Artificial Intelligence", "Data Science", "Internet of Things", "Cybersecurity", "Cloud", "Open Innovation", "Other"],
      },
      { name: "MEMBERS", label: "Team members", type: "textarea", required: true, placeholder: "Separate names using commas" },
      { name: "TECH_STACK", label: "Technology stack", type: "text", required: true },
      { name: "DESCRIPTION", label: "Project description", type: "textarea", required: true },
      {
        name: "STATUS",
        label: "Status",
        type: "select",
        required: true,
        options: ["Idea", "Planning", "In Progress", "Prototype", "Completed", "Deployed"],
      },
      { name: "GITHUB", label: "GitHub URL", type: "url" },
      { name: "DEMO", label: "Live demo URL", type: "url" },
      { name: "IMAGE", label: "Project image URL", type: "url" },
    ],
    detailOrder: ["CATEGORY", "MEMBERS", "TECH_STACK", "DESCRIPTION", "STATUS", "GITHUB", "DEMO"],
  },

  certificates: {
    pageTitle: "Certificates",
    pageSubtitle: "Store course, competition, workshop and professional certification records.",
    sheetName: "Certificates",
    idField: "CERTIFICATE_ID",
    idPrefix: "CRT",
    icon: "📜",
    titleField: "TITLE",
    subtitleField: "ISSUER",
    badgeField: "CATEGORY",
    searchFields: ["ENROLMENT_NUMBER", "TITLE", "ISSUER", "CATEGORY", "STATUS"],
    fields: [
      {
        name: "ENROLMENT_NUMBER",
        label: "Enrolment number",
        type: "text",
        required: true,
        prefill: "ownedEnrolment",
        studentReadOnly: true,
      },
      { name: "TITLE", label: "Certificate title", type: "text", required: true },
      { name: "ISSUER", label: "Issuing organization", type: "text", required: true },
      { name: "DATE", label: "Completion date", type: "date", required: true },
      {
        name: "CATEGORY",
        label: "Category",
        type: "select",
        required: true,
        options: ["Course", "Hackathon", "Workshop", "Competition", "Cloud", "Programming", "Internship", "Presentation", "Other"],
      },
      { name: "FILE_URL", label: "Certificate file URL", type: "url", required: true },
      {
        name: "STATUS",
        label: "Certificate status",
        type: "select",
        required: true,
        options: ["Completed", "Valid", "Expired"],
        defaultValue: "Completed",
      },
    ],
    detailOrder: ["ENROLMENT_NUMBER", "ISSUER", "DATE", "CATEGORY", "STATUS", "FILE_URL"],
  },

  opportunities: {
    pageTitle: "Opportunities",
    pageSubtitle: "Share internships, hackathons, contests, workshops and scholarships with the team.",
    sheetName: "Opportunities",
    idField: "OPPORTUNITY_ID",
    idPrefix: "OPP",
    icon: "🚀",
    titleField: "TITLE",
    subtitleField: "COMPANY",
    badgeField: "TYPE",
    searchFields: ["TITLE", "TYPE", "COMPANY", "ELIGIBILITY", "DEADLINE", "STATUS"],
    fields: [
      { name: "TITLE", label: "Opportunity title", type: "text", required: true },
      {
        name: "TYPE",
        label: "Type",
        type: "select",
        required: true,
        options: ["Internship", "Hackathon", "Coding Contest", "Workshop", "Scholarship", "Certification", "College Event", "Other"],
      },
      { name: "COMPANY", label: "Company / organizer", type: "text", required: true },
      { name: "ELIGIBILITY", label: "Eligibility", type: "textarea", required: true },
      { name: "DEADLINE", label: "Deadline", type: "date", required: true },
      { name: "LINK", label: "Application link", type: "url", required: true },
      {
        name: "STATUS",
        label: "Current status",
        type: "select",
        required: true,
        options: ["Open", "Interested", "Applied", "Selected", "Rejected", "Completed", "Closed"],
        defaultValue: "Open",
      },
    ],
    detailOrder: ["TYPE", "COMPANY", "ELIGIBILITY", "DEADLINE", "STATUS", "LINK"],
  },
};

export const TEAM_PAGE_KEYS = Object.keys(TEAM_SECTION_CONFIGS);
